name: wash_flutter
description: "WashyWash Flutter App - Laundry service application with Clean Architecture"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8

  # HTTP & Networking
  http: ^1.2.2

  # Local Storage
  shared_preferences: ^2.3.2

  # Device Info
  device_info_plus: ^10.1.2

  # URL Launcher
  url_launcher: ^6.3.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^7.7.0
  # connectivity_plus: ^7.0.0  # Temporarily disabled

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets from Java WashyWash project (100% matching)
  assets:
    - assets/images/

  # Fonts from Java project (source_sans_pro)
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/source_sans_pro_regular.otf
        - asset: assets/fonts/source_sans_pro_semibold.otf
          weight: 600
